name: Automatic Dependency Submission

on:
  push:
    branches: [ 'master' ]
  workflow_dispatch:

permissions:
  contents: write

env:
  TERMUX_GRADLE_REMOTE_CACHE_URL: ${{ secrets.TERMUX_GRADLE_REMOTE_CACHE_URL }}
  TERMUX_GRADLE_REMOTE_CACHE_USER: ${{ secrets.TERMUX_GRADLE_REMOTE_CACHE_USER }}
  TERMUX_GRADLE_REMOTE_CACHE_TOKEN: ${{ secrets.TERMUX_GRADLE_REMOTE_CACHE_TOKEN }}

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v6
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v5
