name: Unit tests

on:
  push:
    branches:
      - master
      - android-10
  pull_request:
    branches:
      - master
      - android-10

env:
  TERMUX_GRADLE_REMOTE_CACHE_URL: ${{ secrets.TERMUX_GRADLE_REMOTE_CACHE_URL }}
  TERMUX_GRADLE_REMOTE_CACHE_USER: ${{ secrets.TERMUX_GRADLE_REMOTE_CACHE_USER }}
  TERMUX_GRADLE_REMOTE_CACHE_TOKEN: ${{ secrets.TERMUX_GRADLE_REMOTE_CACHE_TOKEN }}

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v6
    - name: Setup java 17
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Execute tests
      run: |
        ./gradlew test
